### ISSUE TITLE
DateTime field must cast to 'datetime' in Eloquent model.

### ISSUE THREAD

**Issue by matthewjumpsoffbuildings** [outl1ne/nova-page-manager#143]
When I attempt to use a Nova `DateTime` field in an NPM Region, I get this error when attempting to view or edit it

```
DateTime field must cast to 'datetime' in Eloquent model.
```

**Comment by matthewjumpsoffbuildings** [comment]
I discovered if I do this

```php
Panel::make('Calendar', [
  Text::make('Title'),
  DateTime::make('Start Date')->resolveUsing(function($value) { 
    return $value; 
  }),
]),
```
It seems to work?

**Comment by Tarpsvo** [comment]
This should be fixed in version 5.8.5, I manually resolve the field as Carbon now.

**Comment by matthewjumpsoffbuildings** [comment]
@Tarpsvo I updated to 5.8.5, cleared my artisan caches, cleared my browser caches, still getting the same error, unless I use that manual call to `resolveUsing` as I mentioned

**Comment by t1mofe1** [comment]
Error still exists.. 
![image](https://github.com/outl1ne/nova-page-manager/assets/61961709/791bc31f-8c39-4efd-b7e8-65e430fc8ddf)

![image](https://github.com/outl1ne/nova-page-manager/assets/61961709/123fd1be-1536-4cac-981a-8337dc4a8fb3)
![image](https://github.com/outl1ne/nova-page-manager/assets/61961709/78582c8c-30f0-43eb-a448-21b7589f8d09)

Only works with `resolveUsing`
![image](https://github.com/outl1ne/nova-page-manager/assets/61961709/e20775ed-777c-4213-a77d-f5bab55e0079)
