### ISSUE TITLE
Postgres database migration error

### ISSUE THREAD

**Issue by shahruslan** [outl1ne/nova-page-manager#62]
I am using postgres database and I get this error when migrating (`2019_11_29_000005_make_slug_locale_published_parent_id_pair_unique.php`):

```
  SQLSTATE[42601]: Syntax error: 7 ERROR:  syntax error at or near "FROM"
LINE 2:             FROM nova_page_manager_pages
                    ^ (SQL: SHOW KEYS
            FROM nova_page_manager_pages
            WHERE Key_name LIKE 'nova_page_manager_pages%'
            AND Key_name LIKE '%locale_slug_published_unique')
```

This migration is for MySQL only?

And can I skip this migration if my initial `nova_page_manager_pages` table is empty?

**Comment by Tarpsvo** [comment]
Indeed, the SHOW KEYS part only works on MySQL and MariaDB.

I released version 3.1.7 that should address this. Please try it out and do let me know if it works now. Thanks and good luck!

**Comment by shahruslan** [comment]
Thank you for efficiency!
But another error came up:
```
 ErrorException

  The use statement with non-compound name 'Exception' has no effect

  at database/migrations/2019_11_29_000005_make_slug_locale_published_parent_id_pair_unique.php:3
```

**Comment by shahruslan** [comment]
Version 3.1.8

**Comment by Tarpsvo** [comment]
Oopsie. Fixed in version 3.2.0. Good luck!

**Comment by shahruslan** [comment]
Sorry, but I get errors again)

The error still occurs. As I found out, it is because of this code:
```
       try {
           Schema::table($pagesTableName, function ($table) {
               $table->dropUnique("nova_page_manager_pages_locale_slug_published_unique");
           });
       } catch (Exception $e) {
       }
```
Although this suppresses the error output to the console, something happens inside the method and the transaction is not applied. If I comment this out, then everything works well for me.

Therefore, you still need to get the index name and delete it.

**Comment by Tarpsvo** [comment]
Alright, added a third implementation which works on my machine. How about yours? Try out version 3.2.1.

**Comment by shahruslan** [comment]
Excellent. Migration and rollback works well!
